### PR TITLE
Improved "runningInNodeJS" check

### PR DESCRIPTION
**Pull request by TheIronDeveloper**
When in a commonJS environment (like webpack), this library encounters
an infinite loop between `newByteArray` and `convertToByteArray`.

Simply hardening the check to see if we are in a node environment
is enough to prevent the loop from happening. Although this can be
spoofed (like many amIInNodeLand checks), the assumption I am working
off of is window is not initially part of the global environment.

This won't cause new problems, but also isn't bullet proof either.

--

**PR Note**: I ran "grunt", which generated all kinds of magic. Let me know if that is undesired and I can revert the "grunt" and simply add in the runningInNodeJS parts.

### CODE REVIEW

**Comment by rotemdan** [comment]
Thanks for notifying me about the problem and taking the time to try and solve it. I'm aware the simplistic detection method I used wasn't good enough and might break on some platforms. 

As you mentioned the current check isn't really correctly performed (or named) as it doesn't actually detect Node.js, but CommonJS, which might be polyfilled in the browser or available in some other Javascript variant independently from the Node.js API.

The problem with adding `typeof window === "undefined"` is that it is going to break on platforms that have both the Node API (or at least CommonJS), and a DOM (or at least some polyfill for the "window" object). [Node-Webkit](https://github.com/nwjs/nw.js/) is one example (I did have a version with the check on "window" but I removed it).

I should definitely try to find a better way to approach this. Using [process.versions.node](https://nodejs.org/api/process.html#process_process_version) might be an alternative that may actually detect the Node.js API instead of just Common JS. Something like
```ts
 	export function runningInNodeJS()
 	{
		return ((typeof process === "object") && (typeof process.versions === "object") && (typeof process.versions.node === "string"));
 	}
```

I've tested this and it seems to work correctly. I'll commit it later today if I can't find a better solution. 

I should also probably handle the special cases where both Node.js and the DOM are not available and give out some error message in that situation.

**Comment by TheIronDeveloper** [comment]
Hm, I'm actually a much bigger fan of the `process.versions.node` approach. I'm updating the PR now

**Comment by TheIronDeveloper** [comment]
PR updated. Not sure if keeping `(typeof process === "object") && (typeof process.versions === "object")` was desired or not. Let me know your preference and I'll update the PR accordingly.

Thanks!

**Comment by TheIronDeveloper** [comment]
ps, thanks for writing this library! I've been using it as a dependency on a side project and it works great! :+1:

**Comment by rotemdan** [comment]
These checks are needed as Javascript would throw an exception whenever a member of an undefined or null object is accessed. I believe there is some proposal of having an operator that would silently resolve to `undefined` in these situations, not sure about the name. It would work like `typeof process?.versions?.node === "object"`. This might have already been proposed for ES7. I'm not sure.

The thing is, I made the change in my local version of the code, and also updated some of the build dependencies and countered a number breaking changes when upgrading from TypeScript 1.4 to 1.5 Beta (1.5 final would probably be released shortly with RTM version of VS 2015 that is scheduled to be released in a couple of days). 

It's true that the Grunt build script does almost everything automatically (except from updating the release build version - which has to be done manually) but I'm a bit cautious of committing the change through the GitHub interface (at least to the master branch). I haven't looked at this code for a while so I also need to verify that other aspects of the code are working properly (especially the `ByteArray` class that I improved in another project that uses it but didn't propagate the changes yet).

**Comment by rotemdan** [comment]
Although I didn't apply the pull request directly, I committed the change, along with some other minor ones. I also updated the NPM package and the GitHub hosting page. I tested under FF, Chrome, IE9+, Android 4+, Node 0.10, 0.12 and io.js and it seems to be alright. I never actually ran the tests under Node-Webkit or Apache Cordova. I'll try to do that at some point.

It's good to have feedback from someone actually uses the library in practice :). I tried my best to automate the testing process but you never know what kind of problems might occur when actually using it (there may actually still be some rare bugs that have not been addressed).

By the way, although currently unreleased/undocumented, there's a basic node-based command line interface under the `/LZUTF8/CLI` folder. I use it mostly for testing (can work with very large files) and benchmarking (the demo only runs in a browser so it doesn't always reflect the performance under Node, though in the CLI the times measured also include disk I/O so the two should not compared directly):

```
Usage: node lzutf8-cli [command] [source] [destination?]

Commands:
	c   Compress [source] to [destination]
	d   Decompress [source] to [destination]
	t   Test compression and decompression correctness using [source]
```

**Comment by TheIronDeveloper** [comment]
> These checks are needed as Javascript would throw an exception whenever a member of an undefined or null object is accessed

Simply doing a truthy checking before accessing child elements will short-circuit execution (and not throw an exception) :)

**Comment by rotemdan** [comment]
This may actually work, Javascript is a "weird" language so even primitives like booleans are considered to be objects. So even if I set `var process = true`, `var v = process.versions` will evaluate to undefined and not throw an Error. It feels safer to check that these are actual objects though, just for clarity (incorrect types will also be caught earlier this way).

**Comment by TheIronDeveloper** [comment]
Ultimately it all ends up being personal preference. :)

**Pull request closed without merging**
